In [5]:
import pandas as pd

In [7]:
df = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9]], columns = ["A", "B", "C"], index = ["x", "y", "z"])
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [ ]:
df.head(1)
df.head(2)

   A  B  C
x  1  2  3
y  4  5  6

In [13]:
df.tail(2)

   A  B  C
y  4  5  6
z  7  8  9

In [21]:
dfe = pd.DataFrame([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]] ,[[13,14,15], [16,17,18]]], columns = (["A", "B",]))
dfe

              A             B
0     [1, 2, 3]     [4, 5, 6]
1     [7, 8, 9]  [10, 11, 12]
2  [13, 14, 15]  [16, 17, 18]

In [24]:
df.columns

Index(['A', 'B', 'C'], dtype='str')

In [25]:
df.index

Index(['x', 'y', 'z'], dtype='str')

In [27]:
df.info()

<class 'pandas.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 204.0+ bytes

In [28]:
dfe.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      object
 1   B       3 non-null      object
dtypes: object(2)
memory usage: 180.0+ bytes

In [29]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

In [30]:
dfe.describe()

                A          B
count           3          3
unique          3          3
top     [1, 2, 3]  [4, 5, 6]
freq            1          1

In [31]:
df.nunique()

A    3
B    3
C    3
dtype: int64

In [33]:
dfe.shape

(3, 2)

# Loading in dataframes from files
___

In [37]:
coffee = pd.read_csv('./coffee.csv')

In [50]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [3]:
results = pd.read_parquet('./results.parquet')

In [ ]:
!pip install pyarrow

Collecting pyarrow
  Using cached pyarrow-24.0.0-cp314-cp314-win_amd64.whl.metadata (3.0 kB)
Using cached pyarrow-24.0.0-cp314-cp314-win_amd64.whl (28.0 MB)
Installing collected packages: pyarrow
Successfully installed pyarrow-24.0.0

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [7]:
results.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [8]:
!pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
olympics_data = pd.read_excel('olympics-data.xlsx')

In [9]:
olympics_data.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [10]:
olympics_data1 = pd.read_excel('olympics-data.xlsx', sheet_name="results")

In [11]:
olympics_data1.head()

,year,type,discipline,event,as,athlete_id,noc,team,place,tied,medal
0,1912.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,17.0,True,NaN
1,1912.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jean Montariol,NaN,False,NaN
2,1920.0,Summer,Tennis,"Singles, Men (Olympic)",Jean-François Blanchy,1,FRA,NaN,32.0,True,NaN
3,1920.0,Summer,Tennis,"Doubles, Mixed (Olympic)",Jean-François Blanchy,1,FRA,Jeanne Vaussard,8.0,True,NaN
4,1920.0,Summer,Tennis,"Doubles, Men (Olympic)",Jean-François Blanchy,1,FRA,Jacques Brugnon,4.0,False,NaN

In [6]:
bios = pd.read_csv('bios.csv')

In [13]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

# ACCESSING DATA WITH PANDAS
___

In [18]:
coffee.head(10)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [17]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [20]:
# For getting random data form the data set 
coffee.sample()

       Day Coffee Type  Units Sold
12  Sunday    Espresso          45

In [29]:
coffee.sample(10)

         Day Coffee Type  Units Sold
1     Monday       Latte          15
11  Saturday       Latte          35
9     Friday       Latte          35
8     Friday    Espresso          45
13    Sunday       Latte          35
2    Tuesday    Espresso          30
7   Thursday       Latte          30
10  Saturday    Espresso          45
0     Monday    Espresso          25
3    Tuesday       Latte          20

In [33]:
coffee.loc[[0,1,2]]

       Day Coffee Type  Units Sold
0   Monday    Espresso          25
1   Monday       Latte          15
2  Tuesday    Espresso          30

In [34]:
coffee.loc[0:10]

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45

In [35]:
coffee.loc[5:9]

         Day Coffee Type  Units Sold
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45
9     Friday       Latte          35

In [36]:
coffee.loc[0:]  # It means 0 onwards

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [38]:
coffee.loc[5:8, ["Day", "Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [ ]:
coffee.iloc[5:8, [0,2]] #It uses index instead of names

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30

In [40]:
# The difference between loc and iloc is that in loc the upper index is inclusive and in iloc the upper index is exclusive

In [ ]:
# Modifying dataset
coffee.loc[1,"Units Sold"] = 10 # It was 15 before

In [42]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          10
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [43]:
coffee.loc[1:3, "Units Sold"] = 14

In [44]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          14
2     Tuesday    Espresso          14
3     Tuesday       Latte          14
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [45]:
# Now in loc we do not write index and in iloc we write index. But in loc we still need to write 1:3, so to fix that We can do one thing that index = days so that when writing 1:3 we can
# simply write Monday:Wednesday. It is also cnvenient because we do not need to remember index and we can simply search by days

In [46]:
coffee.index = coffee["Day"]

In [47]:
coffee.loc["Monday"]

           Day Coffee Type  Units Sold
Day
Monday  Monday    Espresso          25
Monday  Monday       Latte          14

In [48]:
coffee.loc["Monday":"Tuesday"]

             Day Coffee Type  Units Sold
Day
Monday    Monday    Espresso          25
Monday    Monday       Latte          14
Tuesday  Tuesday    Espresso          14
Tuesday  Tuesday       Latte          14

In [49]:
coffee.loc["Monday":"Tuesday","Units Sold"]

Day
Monday     25
Monday     14
Tuesday    14
Tuesday    14
Name: Units Sold, dtype: int64

In [51]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [ ]:
# To point to a particular value we ca also use "at" and "iat"
# Difference between both is same as loc and iloc as at uses name and iat uses index

In [53]:
coffee.at[0,"Units Sold"]

np.int64(25)

In [55]:
coffee.iat[0,0]

'Monday'

In [56]:
# Sorting values

In [61]:
coffee.sort_values("Units Sold") # Sorts units sold in ascending order. If we want it in decreasingn order then 
coffee.sort_values("Units Sold", ascending = False)

          Day Coffee Type  Units Sold
10   Saturday    Espresso          45
8      Friday    Espresso          45
12     Sunday    Espresso          45
6    Thursday    Espresso          40
4   Wednesday    Espresso          35
11   Saturday       Latte          35
13     Sunday       Latte          35
9      Friday       Latte          35
2     Tuesday    Espresso          30
7    Thursday       Latte          30
0      Monday    Espresso          25
5   Wednesday       Latte          25
3     Tuesday       Latte          20
1      Monday       Latte          15

# Filtering Data

In [62]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [66]:
bios.info()

<class 'pandas.DataFrame'>
RangeIndex: 145500 entries, 0 to 145499
Data columns (total 10 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   athlete_id    145500 non-null  int64
 1   name          145500 non-null  str
 2   born_date     143693 non-null  str
 3   born_city     110908 non-null  str
 4   born_region   110908 non-null  str
 5   born_country  110908 non-null  str
 6   NOC           145499 non-null  str
 7   height_cm     106651 non-null  float64
 8   weight_kg     102070 non-null  float64
 9   died_date     33940 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 18.5 MB

In [67]:
bios.loc[bios['height_cm'] > 210]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5089,5108,Viktor Pankrashkin,1957-06-19,Moskva (Moscow),Moskva,RUS,Soviet Union,220.0,112.0,1993-07-24
5572,5595,Santiago Aldama,1968-12-07,Quel,La Rioja,ESP,Spain,213.0,98.0,NaN
5583,5606,Paulinho Villas Boas,1963-01-26,São Paulo,São Paulo,BRA,Brazil,217.0,106.0,NaN
5599,5622,Vladimir Andreyev,1945-06-14,Astrakhan,Astrakhan,RUS,Soviet Union,215.0,90.0,NaN
5609,5632,Franjo Arapović,1965-06-02,NaN,NaN,NaN,Croatia Yugoslavia,211.0,120.0,NaN
...,...,...,...,...,...,...,...,...,...,...
140298,143804,Aaron Geramipoor,1992-09-11,Stockport,England,GBR,Islamic Republic of Iran,214.0,NaN,NaN
141018,144554,Yuta Watanabe,1994-10-13,Ayauta district,Kagawa,JPN,Japan,215.0,97.0,NaN
142044,145640,Jahlil Okafor,1995-12-15,Fort Smith,Arkansas,USA,Nigeria,211.0,NaN,NaN
142930,146560,Mike Tobey,1994-10-10,Monroe,New York,USA,Slovenia,213.0,NaN,NaN
143712,147367,JaVale McGee,1988-01-19,Flint,Michigan,USA,United States,213.0,NaN,NaN

In [70]:
bios.loc[bios['height_cm'] > 220, ['name', 'height_cm']]

                   name  height_cm
5673     Gunther Behnke      221.0
5781     Tommy Burleson      223.0
6978    Arvydas Sabonis      223.0
89070          Yao Ming      226.0
89075    Roberto Dueñas      221.0
120266     Zhang Zhaoxu      221.0

In [72]:
# Another syntax for the above thing may look like
bios[bios['height_cm'] > 215][["name","height_cm"]]

                         name  height_cm
5089       Viktor Pankrashkin      220.0
5583     Paulinho Villas Boas      217.0
5673           Gunther Behnke      221.0
5716                 Uwe Blab      218.0
5781           Tommy Burleson      223.0
5796            Andy Campbell      218.0
6223              Lars Hansen      216.0
6270              Hu Zhangbao      216.0
6409         Sergey Kovalenko      216.0
6420            Jānis Krūmiņš      218.0
6504              Luc Longley      220.0
6722         Shaquille O'Neal      216.0
6937           David Robinson      216.0
6978          Arvydas Sabonis      223.0
7074           Paulo da Silva      217.0
7188       Vladimir Tkachenko      220.0
7281         Stojko Vranković      217.0
7376      Eurelijus Žukauskas      218.0
52608         Aleksey Kazakov      217.0
82100           Frédéric Weis      218.0
89070                Yao Ming      226.0
89075          Roberto Dueñas      221.0
107408       Peter John Ramos      219.0
112312           Stanko Barać      217.0
112332    Andreas Glyniadakis      216.0
112337          Hamed Haddadi      218.0
118663         Timofey Mozgov      216.0
118676        Dmitry Musersky      219.0
120266           Zhang Zhaoxu      221.0
121694            Salah Mejri      216.0
123850         Tyson Chandler      216.0
130460               Li Muhao      218.0
130461                Zhou Qi      217.0
138671          Ondřej Balvín      216.0
139365         Moustapha Fall      218.0

# Multiple Filter Conditions

In [73]:
bios[(bios['height_cm'] > 215) & (bios['born_country']=='USA')]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
5781,5804,Tommy Burleson,1952-02-24,Crossnore,North Carolina,USA,United States,223.0,102.0,NaN
6722,6755,Shaquille O'Neal,1972-03-06,Newark,New Jersey,USA,United States,216.0,137.0,NaN
6937,6972,David Robinson,1965-08-06,Key West,Florida,USA,United States,216.0,107.0,NaN
123850,126093,Tyson Chandler,1982-10-02,Hanford,California,USA,United States,216.0,107.0,NaN

In [ ]:
# If we want to search names which start with a particular letter or some words then for that
bios[bios['name'].str.contains("Keith")] # Case sensitive

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [76]:
# If we do not want it to be case sensitive then

In [77]:
bios[bios['name'].str.contains("keith", case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22
...,...,...,...,...,...,...,...,...,...,...
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN
117676,119195,Duncan Keith,1983-07-16,Winnipeg,Manitoba,CAN,Canada,185.0,88.0,NaN
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN
127310,129749,Tracy Keith-Matchitt,1990-03-30,Palmerston North,Manawatu-Wanganui,NZL,Cook Islands,167.0,60.0,NaN

In [78]:
# For more than one words
bios[bios['name'].str.contains('keith|patrick', case=False)]

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
6,7,Patrick Chila,1969-11-27,Ris-Orangis,Essonne,FRA,France,180.0,73.0,NaN
119,120,Patrick Wheatley,1899-01-20,Vryheid,KwaZulu-Natal,RSA,Great Britain,NaN,NaN,1967-11-05
319,320,Patrick De Koning,1961-04-23,Dendermonde,Oost-Vlaanderen,BEL,Belgium,178.0,92.0,NaN
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN
2115,2125,Patrick Jopp,1962-01-08,NaN,NaN,NaN,Switzerland,176.0,67.0,NaN
...,...,...,...,...,...,...,...,...,...,...
143975,147633,Patrick Chinyemba,2001-01-03,NaN,NaN,NaN,Zambia,NaN,NaN,NaN
144172,147850,Patrick Jakob,1996-10-17,Sankt Johann in Tirol,Tirol,AUT,Austria,NaN,NaN,NaN
144547,148239,Patrick Galbraith,1986-03-11,Haderslev,Syddanmark,DEN,Denmark,NaN,NaN,NaN
144565,148257,Patrick Russell,1993-01-04,Gentofte,Hovedstaden,DEN,Denmark,186.0,93.0,NaN
145435,149158,Patrick Gasienica,1998-11-28,McHenry,Illinois,USA,United States,NaN,NaN,2023-06-12

In [8]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [ ]:
coffee['Price'] = 4.99 # Adding a new column

In [10]:
coffee.head()

         Day Coffee Type  Units Sold  Price
0     Monday    Espresso          25   4.99
1     Monday       Latte          15   4.99
2    Tuesday    Espresso          30   4.99
3    Tuesday       Latte          20   4.99
4  Wednesday    Espresso          35   4.99

In [38]:
import numpy as np

coffee['new_Price'] = np.where(coffee['Coffee Type'] == 'Espresso', 4.99, 5.99)

In [13]:
coffee

          Day Coffee Type  Units Sold  Price  new_Price
0      Monday    Espresso          25   4.99       4.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       4.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       4.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       4.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       4.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       4.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       4.99
13     Sunday       Latte          35   4.99       5.99

In [ ]:
# Dropping column or row
coffee.drop(0) # It dropped the 0th row but it will not make change in the actual data, like if we print coffee after thisit willl still show the 0th row

          Day Coffee Type  Units Sold  Price  new_Price
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       4.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       4.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       4.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       4.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       4.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       4.99
13     Sunday       Latte          35   4.99       5.99

In [16]:
coffee

          Day Coffee Type  Units Sold  Price  new_Price
0      Monday    Espresso          25   4.99       4.99
1      Monday       Latte          15   4.99       5.99
2     Tuesday    Espresso          30   4.99       4.99
3     Tuesday       Latte          20   4.99       5.99
4   Wednesday    Espresso          35   4.99       4.99
5   Wednesday       Latte          25   4.99       5.99
6    Thursday    Espresso          40   4.99       4.99
7    Thursday       Latte          30   4.99       5.99
8      Friday    Espresso          45   4.99       4.99
9      Friday       Latte          35   4.99       5.99
10   Saturday    Espresso          45   4.99       4.99
11   Saturday       Latte          35   4.99       5.99
12     Sunday    Espresso          45   4.99       4.99
13     Sunday       Latte          35   4.99       5.99

In [ ]:
coffee.drop(columns = ['Price']) # It will also make no change in the actual data

          Day Coffee Type  Units Sold  new_Price
0      Monday    Espresso          25       4.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       4.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       4.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       4.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       4.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       4.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       4.99
13     Sunday       Latte          35       5.99

In [19]:
# If we want to actually modify it then for that
coffee.drop(columns = ['Price'], inplace = True)

In [20]:
coffee

          Day Coffee Type  Units Sold  new_Price
0      Monday    Espresso          25       4.99
1      Monday       Latte          15       5.99
2     Tuesday    Espresso          30       4.99
3     Tuesday       Latte          20       5.99
4   Wednesday    Espresso          35       4.99
5   Wednesday       Latte          25       5.99
6    Thursday    Espresso          40       4.99
7    Thursday       Latte          30       5.99
8      Friday    Espresso          45       4.99
9      Friday       Latte          35       5.99
10   Saturday    Espresso          45       4.99
11   Saturday       Latte          35       5.99
12     Sunday    Espresso          45       4.99
13     Sunday       Latte          35       5.99

In [23]:
# If we want to make a copy of the data then we can use two types. First is simple equal to where both will point at the same memory location but if we use copy then we will create two different
#memory locations
coffee_new = coffee #Thi points both to the same memore location
coffee_new1 = coffee.copy() #This will create two different memory locations an d changing in one will not change the other

In [ ]:
# We can also do the column removal by
#coffee = coffee.drop(columns = ['new_Price'])

In [29]:
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [34]:
# If lets say there are 100 columns and we only need some of them then for that 
coffee = coffee[['Day', 'Coffee Type']]

In [35]:
coffee

          Day Coffee Type
0      Monday    Espresso
1      Monday       Latte
2     Tuesday    Espresso
3     Tuesday       Latte
4   Wednesday    Espresso
5   Wednesday       Latte
6    Thursday    Espresso
7    Thursday       Latte
8      Friday    Espresso
9      Friday       Latte
10   Saturday    Espresso
11   Saturday       Latte
12     Sunday    Espresso
13     Sunday       Latte

In [40]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_Price']

In [41]:
coffee

          Day Coffee Type  Units Sold  new_Price  revenue
0      Monday    Espresso          25       4.99   124.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       4.99   149.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       4.99   174.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       4.99   199.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       4.99   224.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       4.99   224.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       4.99   224.55
13     Sunday       Latte          35       5.99   209.65

In [ ]:
# If we want to rename a column then
coffee.rename(columns = {'new_Price' : 'Price'}) # but this temporary

          Day Coffee Type  Units Sold  Price  revenue
0      Monday    Espresso          25   4.99   124.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   4.99   149.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   4.99   174.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   4.99   199.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   4.99   224.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   4.99   224.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   4.99   224.55
13     Sunday       Latte          35   5.99   209.65

In [43]:
coffee

          Day Coffee Type  Units Sold  new_Price  revenue
0      Monday    Espresso          25       4.99   124.75
1      Monday       Latte          15       5.99    89.85
2     Tuesday    Espresso          30       4.99   149.70
3     Tuesday       Latte          20       5.99   119.80
4   Wednesday    Espresso          35       4.99   174.65
5   Wednesday       Latte          25       5.99   149.75
6    Thursday    Espresso          40       4.99   199.60
7    Thursday       Latte          30       5.99   179.70
8      Friday    Espresso          45       4.99   224.55
9      Friday       Latte          35       5.99   209.65
10   Saturday    Espresso          45       4.99   224.55
11   Saturday       Latte          35       5.99   209.65
12     Sunday    Espresso          45       4.99   224.55
13     Sunday       Latte          35       5.99   209.65

In [47]:
# To make it permannet 
coffee.rename(columns = {'new_Price' : 'Price'}, inplace = True) #OR
coffee = coffee.rename(columns = {'new_Price' : 'Price'})

In [48]:
coffee

          Day Coffee Type  Units Sold  Price  revenue
0      Monday    Espresso          25   4.99   124.75
1      Monday       Latte          15   5.99    89.85
2     Tuesday    Espresso          30   4.99   149.70
3     Tuesday       Latte          20   5.99   119.80
4   Wednesday    Espresso          35   4.99   174.65
5   Wednesday       Latte          25   5.99   149.75
6    Thursday    Espresso          40   4.99   199.60
7    Thursday       Latte          30   5.99   179.70
8      Friday    Espresso          45   4.99   224.55
9      Friday       Latte          35   5.99   209.65
10   Saturday    Espresso          45   4.99   224.55
11   Saturday       Latte          35   5.99   209.65
12     Sunday    Espresso          45   4.99   224.55
13     Sunday       Latte          35   5.99   209.65

In [9]:
bios.head()

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25

In [7]:
bios_new = bios.copy()

In [11]:
bios_new['First_name'] = bios_new['name'].str.split(' ').str[0]

In [12]:
bios_new

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,First_name
0,1,Jean-François Blanchy,1886-12-12,Bordeaux,Gironde,FRA,France,NaN,NaN,1960-10-02,Jean-François
1,2,Arnaud Boetsch,1969-04-01,Meulan,Yvelines,FRA,France,183.0,76.0,NaN,Arnaud
2,3,Jean Borotra,1898-08-13,Biarritz,Pyrénées-Atlantiques,FRA,France,183.0,76.0,1994-07-17,Jean
3,4,Jacques Brugnon,1895-05-11,Paris VIIIe,Paris,FRA,France,168.0,64.0,1978-03-20,Jacques
4,5,Albert Canet,1878-04-17,Wandsworth,England,GBR,France,NaN,NaN,1930-07-25,Albert
...,...,...,...,...,...,...,...,...,...,...,...
145495,149222,Polina Luchnikova,2002-01-30,Serov,Sverdlovsk,RUS,ROC,167.0,61.0,NaN,Polina
145496,149223,Valeriya Merkusheva,1999-09-20,Moskva (Moscow),Moskva,RUS,ROC,168.0,65.0,NaN,Valeriya
145497,149224,Yuliya Smirnova,1998-05-08,Kotlas,Arkhangelsk,RUS,ROC,163.0,55.0,NaN,Yuliya
145498,149225,André Foussard,1899-05-19,Niort,Deux-Sèvres,FRA,France,166.0,NaN,1986-03-18,André
145499,149814,Bill Phillips,1913-07-15,Dulwich Hill,New South Wales,AUS,Australia,NaN,NaN,2003-10-20,Bill

In [13]:
bios_new.query('First_name == "Keith"')

,athlete_id,name,born_date,born_city,born_region,born_country,NOC,height_cm,weight_kg,died_date,First_name
1897,1907,Keith Hanlon,1966-09-01,NaN,NaN,NaN,Ireland,NaN,NaN,NaN,Keith
3505,3517,Keith Wallace,1961-03-29,Preston,England,GBR,Great Britain,165.0,51.0,1999-12-31,Keith
6228,6255,Keith Hartley,1940-10-15,Vancouver,British Columbia,CAN,Canada,200.0,85.0,NaN,Keith
8898,8946,Keith Mwila,1966-01-01,NaN,NaN,NaN,Zambia,NaN,NaN,1993-01-09,Keith
12053,12118,Keith Hervey,1898-11-03,Fulham,England,GBR,Great Britain,NaN,NaN,1973-02-22,Keith
...,...,...,...,...,...,...,...,...,...,...,...
99921,100722,Keith Carney,1970-02-03,Providence,Rhode Island,USA,United States,188.0,93.0,NaN,Keith
102227,103168,Keith Beavers,1983-02-09,London,Ontario,CAN,Canada,185.0,75.0,NaN,Keith
109900,111105,Keith Cumberpatch,1927-08-25,Christchurch,Canterbury,NZL,New Zealand,NaN,NaN,2013-11-15,Keith
115973,117348,Keith Sanderson,1975-02-02,Plymouth,Massachusetts,USA,United States,183.0,95.0,NaN,Keith
122121,124176,Keith Ferguson,1979-09-07,Sale,Victoria,AUS,Australia,176.0,78.0,NaN,Keith

# Merging and Concatenating data